### ISSUE TITLE
Baseinfo 5 not sharing data

### ISSUE THREAD

**Issue by nimrod46** [bloofi/CnC_TA#1] opened 2021-03-02 00:51 UTC
Hi, we can't see other player's info and scan results, any idea what the cause is?

**Comment by nimrod46** [comment] 2021-03-04 11:03
@bloofi are you still working on it?

**Comment by bloofi** [comment] 2021-03-04 16:43
Hi nimrod46,

Sorry for late answer :)
Yes i'm still working on it.
The most frequent cause for people not seeing other people in the webapp (infos & scans) is because they are **trial** ingame. Try set them as **member** in the alliance.
If they still doesn't see things, DM me the world & players involved and i'll take a look at the issue.

Anyway, i should release an update soon, to fix some minor bugs.

**Comment by nimrod46** [comment] 2021-03-04 22:08
Hi @bloofi, thanks for the help! Do you mean DM in here?

In world Tib 48 my acc name is `*****`, in alliance `*****`, I can't seem to fetch other players data:
![Untitled](https://user-images.githubusercontent.com/11810541/110036026-1268b700-7d45-11eb-958d-1abb1de76997.png)

 I can confirm this worked in the past and I am a Member in my alliance.
 Any other players that I happen to ask in my alliance experience the same thing as me, so I won't write their names, but if you do need more information tell me!

This is also true for the layouts page, I can only view my own scanned layouts

I will redact some information after your response so don't quote me :)

**Comment by bloofi** [comment] 2021-03-04 23:16
Do you have something set in the filters ?
I'll take a look at your issue.

**Comment by nimrod46** [comment] 2021-03-04 23:26
> Do you have something set in the filters ?

No, the same goes for the layout page, I only see mine. 
No console messages either, only:
> Authenticating using token in URL .....

Thanks again!

**Comment by bloofi** [comment] 2021-03-04 23:31
Did you have something in filter sooner during this server ? And did you changed alliance at some point ?

**Comment by bloofi** [comment] 2021-03-04 23:37
I just checked, you are marked as Newbie in baseinfo database (trial).
Also, these players are marked as Newbie : ADMonster, Barathas, BITALT, carabmac2, clanwolf6, daddo2, DennysGraph, FarnDallas, HEINKICKED, HIghtable34, rd054.

**Comment by nimrod46** [comment] 2021-03-04 23:38
> I just checked, you are marked as Newbie in baseinfo database (trial).
> Also, these players are marked as Newbie : ADMonster, Barathas, BITALT, carabmac2, clanwolf6, daddo2, DennysGraph, FarnDallas, HEINKICKED, HIghtable34, rd054.

Damn, they are in my alliance, all of them, why did it happen?
Closed the issue by mistake

**Comment by bloofi** [comment] 2021-03-04 23:39
Are these players really "trial" ingame ?

**Comment by nimrod46** [comment] 2021-03-04 23:40
> Are these players really "trial" ingame ?

No, rd is our SC for example

**Comment by bloofi** [comment] 2021-03-04 23:47
He has been set SiC between my first and second check, he was Newbie like 15min ago ^^. Or maybe he didnt update his baseinfo since then.

**Comment by nimrod46** [comment] 2021-03-04 23:52
> He has been set SiC between my first and second check, he was Newbie like 15min ago ^^. Or maybe he didnt update his baseinfo since then.

I don't know, we only have one trail player and he is not on this list.
rd is SiC since he had this script, no one was on trail status it has to be a bug.

**Comment by bloofi** [comment] 2021-03-04 23:53
i'll try to reproduce this issue on my side

**Comment by nimrod46** [comment] 2021-03-04 23:54
You have other checks to see if a player should be considered Newbie? I guess it just gets falsely triggered

**Comment by nimrod46** [comment] 2021-03-04 23:55
Also, we are the only players in that world who use this script?

**Comment by bloofi** [comment] 2021-03-04 23:55
Your game language is english ?

**Comment by nimrod46** [comment] 2021-03-04 23:55
> Your game language is english ?

Yes

**Comment by bloofi** [comment] 2021-03-04 23:56
There are actually 400+ players registered for this world.

**Comment by nimrod46** [comment] 2021-03-04 23:56
rd should be able to see other player's info? should I check with him?

**Comment by bloofi** [comment] 2021-03-04 23:56
yes, he should be able to see

**Comment by bloofi** [comment] 2021-03-05 00:03
Can you confirm that everyone uses baseinfo v5 in your alliance ?
Also, did you remember to uninstall previous versions of baseinfo if you had any of them ?

**Comment by nimrod46** [comment] 2021-03-05 00:03
> yes, he should be able to see

It's not showing him any other player's data, maybe because everyone else is blocked?

Also there are more players than you mentioned in my alliance that use it, they all experience the same thing

**Comment by nimrod46** [comment] 2021-03-05 00:06
> Can you confirm that everyone uses baseinfo v5 in your alliance ?
> Also, did you remember to uninstall previous versions of baseinfo if you had any of them ?

Well, they also use ver4 as this version stopped worked, cant tell you if they had version 4 before.

ver 4 is just disabled for me, should I remove it completely?

**Comment by bloofi** [comment] 2021-03-05 00:11
Well, i no longer support this version, so you should remove it yes.
I may have found the issue, i'll push a quick fix now and see if that changes something for you in the next few minutes

**Comment by bloofi** [comment] 2021-03-05 00:24
Ok, looks like the quick fix wasn't enough.
I've put some temporary additionnal rights to the Newbie players so they can view infos & scans, until i find the real issue.
Sorry for inconvenience :/

**Comment by nimrod46** [comment] 2021-03-05 00:52
> Ok, looks like the quick fix wasn't enough.
> I've put some temporary additionnal rights to the Newbie players so they can view infos & scans, until i find the real issue.
> Sorry for inconvenience :/

No worries, thanks!

Can you confirm other, from other alliances also have an irregular number of newbies or is it just us?

**Closed as completed** 2021-03-13 09:02 UTC
